OszTiemTILK/SchuelerManager

SchuelerVerwaltung/src/anwendungslogik/AngabenZurPerson.java, SchuelerVerwaltung/src/anwendungslogik/Kontaktdaten.java, SchuelerVerwaltung/src/anwendungslogik/SchülerIn.java
Erweiterung der Attribute in Klasse SchülerIn.
Kleine Bearbeitung in Klasse AngabenZuPersonen.
=> Bearbeitung der Klassen.

SchuelerVerwaltung/src/anwendungslogik/Adresse.java, SchuelerVerwaltung/src/anwendungslogik/AngabenZurPerson.java, SchuelerVerwaltung/src/anwendungslogik/ErziehungsberechtigteR.java, SchuelerVerwaltung/src/anwendungslogik/Herkunft.java, SchuelerVerwaltung/src/anwendungslogik/Kontaktdaten.java, SchuelerVerwaltung/src/anwendungslogik/MaintestBryan.java, SchuelerVerwaltung/src/anwendungslogik/Sprachen.java
Mthode		in 	Adresse
AngabenZurPerson
ErziehungsberechtigteR
Herkunft
Kontaktdaten
Sprachen
MaintestBryan erstellt
führt oben genannte methoden aus
=> Methode: 	AusgebenZusammenfassung... erstellt

SchuelerVerwaltung/src/anwendungslogik/AngabenZurPerson.java, SchuelerVerwaltung/src/anwendungslogik/ErziehungsberechtigteR.java, SchuelerVerwaltung/src/anwendungslogik/Herkunft.java, SchuelerVerwaltung/src/anwendungslogik/Kontaktdaten.java, SchuelerVerwaltung/src/anwendungslogik/MaintestBryan.java, SchuelerVerwaltung/src/anwendungslogik/SchülerIn.java, SchuelerVerwaltung/src/anwendungslogik/Schülerverhältnisse.java, SchuelerVerwaltung/src/anwendungslogik/Sprachen.java
Methode:  ausgeben() bei fast allen Methoden einfefügt
=> Methode:  ausgeben() bei fast allen Methoden einfefügt

SchuelerVerwaltung/src/anwendungslogik/Adresse.java, SchuelerVerwaltung/src/anwendungslogik/AllgemeinbildendeSchule.java, SchuelerVerwaltung/src/anwendungslogik/AngabenZurPerson.java, SchuelerVerwaltung/src/anwendungslogik/SchülerIn.java
=> Konstruktoren in den Klassen erstellt

SchuelerVerwaltung/src/fx/TestMaske AdresseView.fxml, SchuelerVerwaltung/src/fx/TestMaskeAdresseController.java
=> Adresse angelegt

SchuelerVerwaltung/src/fx/SprachenView.fxml
=> international deleted

SchuelerVerwaltung/src/fx/SprachenController.java
=> methode gemact

SchuelerVerwaltung/src/anwendungslogik/AngabenZurPerson.java, SchuelerVerwaltung/src/anwendungslogik/Geschlecht.java, SchuelerVerwaltung/src/datenbank/Datenbankverbindung.java, SchuelerVerwaltung/src/fx/AgDController.java
-Datenbankverbindung hinzugefügt (aus Fahrradausleihe kopiert)
-Geschlecht: fromString(),toString() hinzugefügt
-AngabenzurPerson: Konstruktor hinzugefügt 
-AgDController: Konstruktoraufruf verändert
=> bearbeitung angabenzuperson

SchuelerVerwaltung/src/anwendungslogik/AngabenZurPerson.java, SchuelerVerwaltung/src/anwendungslogik/SchülerInID.java, SchuelerVerwaltung/src/fx/AgDController.java, SchuelerVerwaltung/src/fx/AngabenZurPersonProgramm.java
=> angabenzuperson hinzugefügt

SchuelerVerwaltung/src/anwendungslogik/Kontaktdaten.java, SchuelerVerwaltung/src/datenbank/VerbindungKontaktdaten.java
Kontaktdaten konstruktoren erstellt und speichernDB() auslesenDB()
erstellt
=> Klasse VerbindungKontaktdaten erstellt

SchuelerVerwaltung/src/fx/Maske_1_1_AgDView.fxml
=> -controller-verknüpfung in der view datei hinzugefügt

SchuelerVerwaltung/src/Schullaufbahn/DBVerbindungSchullaufbahn.java, SchuelerVerwaltung/src/Schullaufbahn/MaintestBryan2.java, SchuelerVerwaltung/src/Schullaufbahn/Schule.java, SchuelerVerwaltung/src/Schullaufbahn/SchullaufbahnController.java, SchuelerVerwaltung/src/Schullaufbahn/SchullaufbahnView.fxml, SchuelerVerwaltung/src/Schullaufbahn/SchülerID.java
Controller bearbeitet
entsprechende Klasse verändert
SchülerID bearbeitet
SchullaufbahnView bearbeitet
DBVerbindungSchullaufbahn erstellt
MaintestBryan2 erstellt
=> Package Schullaufbahn erstellt

SchuelerVerwaltung/src/kontaktdaten/Kontaktdaten.java, SchuelerVerwaltung/src/kontaktdaten/KontaktdatenController.java
=> Controller suchen

SchuelerVerwaltung/src/lehrmittel/Lehrmittel.java, SchuelerVerwaltung/src/lehrmittel/LehrmittelController.java, SchuelerVerwaltung/src/lehrmittel/Maske_6_2_LehrmittelView.fxml
View verändert
Controller Neue Methoden Hinzugefügt
=> Holen der Daten Verbessert in der Klasse Lehrmittel

SchuelerVerwaltung/src/anwendungslogik/SchülerIn.java, SchuelerVerwaltung/src/lehrmittel/AusgeliehenLehrmittel.java
=> AusgeliehenLehrmittel in SchülerIn hinzugefügt, AusgliehenLehrmittel

SchuelerVerwaltung/src/kontaktdaten/Kontaktdaten.java, SchuelerVerwaltung/src/kontaktdaten/KontaktdatenController.java, SchuelerVerwaltung/src/kontaktdaten/KontaktdatenID.java, SchuelerVerwaltung/src/kontaktdaten/KontaktdatenView.fxml
entsprechende KontaktdatenID's ausliest und ausgiebt. 
Im zuge dessen wurden alle vier hier hochgeladenen Klassen bearbeitet
(sei es nur um einen falsch belegten Button in der View Datei zu
beheben)
May the Force be with you!
=> implementierung einer Methode die aus eingegebenen Schülernamen

SchuelerVerwaltung/src/kontaktdaten/KontaktdatenController.java, SchuelerVerwaltung/src/kontaktdaten/KontaktdatenView.fxml
=> Anzeigen einer Fehlermeldung bei nichtvorhandensein eines

SchuelerVerwaltung/src/kontaktdaten/Kontaktdaten.java, SchuelerVerwaltung/src/kontaktdaten/KontaktdatenController.java
Hallo Bearbeiter dieser Zeilen.
Vielen dank für deine Mühen.
*Schleim*
=> Fehlerbehebung in der Speichern Methode

SchuelerVerwaltung/src/kontaktdaten/KontaktdatenController.java
Implementierung der "ausgebenParent" Methode und der "Deutsch" &
"Englisch" methoden
=> Rausschmiss des Notfallbuttons im Controller (btStepIntoTheLight)

SchuelerVerwaltung/src/kontaktdaten/KontaktdatenController.java
Add buttons in controller (btDeutsch und btEnglisch)Add buttons in controller (btDeutsch und btEnglisch)Add buttons in controller (btDeutsch und btEnglisch)Add buttons in controller (btDeutsch und btEnglisch)Add buttons in controller (btDeutsch und btEnglisch)Add buttons in controller (btDeutsch und btEnglisch)Add buttons in controller (btDeutsch und btEnglisch)Add buttons in controller (btDeutsch und btEnglisch)Add buttons in controller (btDeutsch und btEnglisch)Add buttons in controller (btDeutsch und btEnglisch)Add buttons in controller (btDeutsch und btEnglisch)Add buttons in controller (btDeutsch und btEnglisch)Add buttons in controller (btDeutsch und btEnglisch)Add buttons in controller (btDeutsch und btEnglisch)Add buttons in controller (btDeutsch und btEnglisch)Add buttons in …
=> Add buttons in controller (btDeutsch und btEnglisch)

SchuelerVerwaltung/src/kontaktdaten/KontaktdatenView.fxml
=> email feld größer gemacht
